#!/bin/bash

# automatically change configuration of Mac OS X based on location
# author: Domenico Silletti <domenico.silletti@gmail.com>
# version: 0.5.0

# previous release by: Rocco Georgi <rocco@pavingways.com>
# version: 0.4.0

# original author: Onne Gorter <o.gorter@gmail.com>
# url: http://tech.inhelsinki.nl/locationchanger/
# version: 0.4

# redirect all IO to a logfile
mkdir -p /usr/local/var/log
exec &>/usr/local/var/log/locationchanger.log
# redirect all IO to /dev/null (comment this in if you don#t want to write to logfile)
#exec 1>/dev/null 2>/dev/null

# get a little breather before we get data for things to settle down
sleep 2


# get SSID
SSID=`/System/Library/PrivateFrameworks/Apple80211.framework/Versions/A/Resources/airport -I | awk '/ SSID:/ {print $2}'`
echo `date` "New SSID found: $SSID"

# current location var
CURRENT_LOCATION=`scselect | sed '1d' | grep '*' | sed 's/.*(\(.*\))/\1/'`

# LOCATIONS
# (change the location names to match your MAC configuration, verify the location name withthe scselect command from CLI)
# ============================================================
LOCATION_HOME="Home"
LOCATION_WORK="Work"
LOCATION_AUTOMATIC="Automatic"  #Automatic location in case of no match, should be "Automatic", check with scselect command from CLI

# SSIDS
# (change the SSID names to match your Wi-Fi networks)
# ============================================================
SSID_HOME="Home-Wifi-SSID"
SSID_WORK="Company-Wifi-SSID"


# SSID -> LOCATION mapping
case $SSID in
	$SSID_HOME )
		if [ $CURRENT_LOCATION != "$LOCATION_HOME" ]
		then
			scselect "$LOCATION_HOME"
			osascript -e 'display notification "Network Location Changed to '$LOCATION_HOME'" with title "Network Location Changed"'
			echo "--> Location changed to: $LOCATION_HOME"
		else
			echo "--> No change, location was already: $LOCATION_HOME"

		fi
	;;
	$SSID_WORK )
		if [ $CURRENT_LOCATION != "$LOCATION_WORK" ]
		then
			scselect "$LOCATION_WORK"
			osascript -e 'display notification "Network Location Changed to '$LOCATION_WORK'" with title "Network Location Changed"'
			echo "--> Location changed to: $LOCATION_WORK"
		else
			echo "--> No change, location was already: $LOCATION_WORK"

		fi
	;;
	* )
		if [ $CURRENT_LOCATION != "$LOCATION_AUTOMATIC" ]
		then
			scselect "$LOCATION_AUTOMATIC"
			osascript -e 'display notification "Network Location Changed to '$LOCATION_AUTOMATIC'" with title "Network Location Changed"'
			echo "--> Location changed to: $LOCATION_AUTOMATIC"
		else
			echo "--> No change, location was already: $LOCATION_AUTOMATIC"
		fi
	;;
esac




exit 0
